import { generativeAIService } from '../../../services/ai';

export async function generateImageWithAI(context: string, sessionId: string | null | undefined) {
  try {
    // Create vocabulary-rich prompt for the image generation model
    const enhancedPrompt = await createVocabularyRichPrompt(context);
    console.log('📝 Enhanced prompt for image generation:', enhancedPrompt);
    
    const response = await generativeAIService.generateImage({
      prompt: enhancedPrompt,
      n: 1,
      size: '1024*1024'
    });

    if (!response || response.length === 0 || !response[0].url) {
      throw new Error('No image was generated or URL is missing');
    }

    const imageUrl = response[0].url;
    const imageId = `ai_gen_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    
    return {
      id: imageId,
      url: imageUrl,
      alt_description: `A detailed scene showing ${context}`,
      description: `AI-generated image depicting ${context} with rich vocabulary opportunities`,
      prompt: enhancedPrompt,
      source: 'dall-e' as const
    };
  } catch (error) {
    console.error('Error generating image with AI service:', error);
    throw new Error(`Failed to generate AI image: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

async function createVocabularyRichPrompt(context: string): Promise<string> {
  try {
    const prompt = `Create a simple scene description for an image generation model showing: "${context}"

Keep it directly related to ${context}. Show typical objects, tools, and activities found in/for ${context}.

Generate ONLY the scene description, no explanations.`;

    const generatedScene = await generativeAIService.generateText({
      prompt: prompt,
    });
    
    if (!generatedScene) {
      throw new Error('No scene generated by LLM');
    }

    return `${generatedScene}, realistic photography style, detailed and clear, rich in visual elements for vocabulary learning`;
    
  } catch (error) {
    console.error('Error generating prompt with LLM:', error);
    return `${context}, realistic photography style, detailed scene with multiple objects and elements, rich in visual details for vocabulary learning`;
  }
}